name: Deploy to Firebase
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
          directory: ./functions
          file_name: .env

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build_and_deploy_app:
    runs-on: ubuntu-latest
    needs: build_and_deploy_functions
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          directory: ./app
          file_name: .env.development.local

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run prettier
        run: yarn run prettier

      - name: Run linter
        run: yarn run lint

      - name: Run tests
        run: yarn run test

      - name: Build and export
        run: yarn run build && yarn run export

      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAG_CHALLENGE }}"
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
